services:
  - type: web
    name: telegram-player-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python player.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.10.13"
